<a href="https://colab.research.google.com/github/udaycodespace/DeepLearning-Notes/blob/main/handwritten_digit_recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Case Study: Handwritten Digit Recognition using CNN (LeNet-5 inspired)

## 1️⃣ Aim of the Experiment

- To recognize handwritten digits (0–9) automatically from images using a Convolutional Neural Network (CNN).  
- To understand and apply the LeNet-5 inspired CNN architecture on a real dataset.

## 2️⃣ Dataset Used: MNIST

- **MNIST** = Modified NIST dataset, standard for handwritten digit recognition.

- **NIST Versions:**
  1. **NIST-1:** original dataset by US National Institute of Standards and Technology.  
  2. **NIST-2:** modified, preprocessed into 28×28 grayscale images, easier for neural networks.

- **Quantity:**
  - 60,000 training images  
  - 10,000 test images

- **Image properties:**
  - Size: 28×28 pixels  
  - Color: grayscale (0–255 pixel values)  
  - Normalized to 0–1 before feeding into CNN

## 3️⃣ Real-Life Applications

- Automatic postal code recognition in postal services  
- Bank check digit reading  
- OCR (Optical Character Recognition) for digit input in forms, invoices  
- Digital pen / smartboard recognition systems



## 4️⃣ Code

Here is the compact exam-friendly code with simplified variable names:

In [1]:
import tensorflow as tf, cv2, numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Input, Conv2D, AveragePooling2D, Flatten, Dense
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from google.colab import files  # Remove if not using Colab

In [2]:
# 1️⃣ Load data
(a,b),(c,d)=mnist.load_data()
a=a.reshape(-1,28,28,1)/255; c=c.reshape(-1,28,28,1)/255
b=to_categorical(b,10)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [3]:
# 2️⃣ Build CNN (LeNet-5 inspired)
m=Sequential([
    Input(shape=(28,28,1)),
    Conv2D(6,(5,5),activation="tanh",padding="same"), AveragePooling2D(pool_size=(2,2)),
    Conv2D(16,(5,5),activation="tanh"), AveragePooling2D(pool_size=(2,2)),
    Flatten(), Dense(120,activation="tanh"), Dense(84,activation="tanh"), Dense(10,activation="softmax")
])
m.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [4]:
# 3️⃣ Train
m.fit(a,b,epochs=5,batch_size=128,validation_split=0.1,verbose=2)

Epoch 1/5
422/422 - 9s - 21ms/step - accuracy: 0.8934 - loss: 0.3621 - val_accuracy: 0.9603 - val_loss: 0.1358
Epoch 2/5
422/422 - 2s - 4ms/step - accuracy: 0.9595 - loss: 0.1338 - val_accuracy: 0.9745 - val_loss: 0.0842
Epoch 3/5
422/422 - 2s - 4ms/step - accuracy: 0.9733 - loss: 0.0877 - val_accuracy: 0.9773 - val_loss: 0.0725
Epoch 4/5
422/422 - 1s - 3ms/step - accuracy: 0.9808 - loss: 0.0633 - val_accuracy: 0.9825 - val_loss: 0.0604
Epoch 5/5
422/422 - 1s - 3ms/step - accuracy: 0.9841 - loss: 0.0499 - val_accuracy: 0.9832 - val_loss: 0.0589


In [5]:
# 4️⃣ Evaluate
e=np.argmax(m.predict(c),axis=1)
print("Accuracy :", accuracy_score(d,e))
print("Precision:", precision_score(d,e,average='weighted'))
print("Recall   :", recall_score(d,e,average='weighted'))
print("F1-score :", f1_score(d,e,average='weighted'))
print("Confusion:\n", confusion_matrix(d,e))

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Accuracy : 0.9776
Precision: 0.9779711178333852
Recall   : 0.9776
F1-score : 0.9776381958454241
Confusion:
 [[ 968    0    1    0    0    2    3    2    2    2]
 [   0 1124    1    3    0    0    2    2    3    0]
 [   4    2  983   23    0    1    0   16    3    0]
 [   0    0    1  998    0    4    0    5    2    0]
 [   0    0    0    1  960    0    4    2    0   15]
 [   2    0    0    9    0  877    2    1    0    1]
 [   4    2    0    0    2   13  936    0    1    0]
 [   1    1    6    5    0    0    0 1014    0    1]
 [   3    0    1   14    1    3    0    6  944    2]
 [   1    2    0   10    6    8    0    8    2  972]]


In [6]:
# 5️⃣ Save model
m.save("lenet5_mnist.h5")

In [7]:
# 6️⃣ Predict custom handwritten digit
u=files.upload()
for f in u.keys():
    i=cv2.imread(f,0); i=cv2.resize(255-i,(28,28))/255; i=i.reshape(1,28,28,1)
    print("Predicted Digit:", np.argmax(m.predict(i)))

Saving 6.jpeg to 6.jpeg
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 628ms/step
Predicted Digit: 6


## 5️⃣ Explanation / Phases of Case Study!

### Data Collection & Preprocessing
- Load MNIST dataset `(a,b,c,d)`  
- Reshape to `(28×28×1)` for CNN  
- Normalize pixel values to `0–1`  
- One-hot encode labels for classification  

### Model Building
- Build LeNet-5 inspired CNN:  
  - `Conv + Pool → Conv + Pool → Flatten → Dense → Dense → Output`  
- Compile model with **Adam optimizer** and **categorical crossentropy loss**  

### Training the Model
- Train CNN on **60,000 training images**  
- Use **validation split 10%**  
- **Epochs = 5**, **batch size = 128**  

### Evaluation
- Predict test set labels `(c)`  
- Calculate **accuracy, precision, recall, F1-score**  
- Generate **confusion matrix** to visualize performance  

### Deployment / Custom Prediction
- Upload your handwritten digit image  
- Preprocess image (**grayscale, resize 28×28, invert if needed**)  
- Predict digit using trained model  

### ✅ Key Points to Write in Exam
- MNIST dataset is **28×28 grayscale**, 60k train / 10k test  
- LeNet-5 inspired CNN → **2 conv layers + 2 pooling + 2 dense + output**  
- **All metrics printed** → shows model performance clearly  
- Can predict **custom handwritten digits**
